name: Continuous Integration

on:
  workflow_call:
    inputs:
      node-versions:
        description: "Array of Node versions to test on, in string format"
        required: true
        type: string
      prettier-version:
        description: "Prettier version to lint on, in string format"
        required: true
        type: string
    secrets:
      private-ssh-keys:
        description: "Array of private packages SSH deploy keys, in string format"
        required: false

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.node-versions) }}
    steps:
      - name: "Set up GitHub repository"
        uses: actions/checkout@v2
      - name: "Set up Node"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Set up private packages SSH keys"
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.ssh-keys }}
      - name: "Install Node dependencies"
        run: npm install-clean
      - name: "Run tests"
        run: make test
