name: Continuous Integration


on:
  workflow_call:
    inputs:
      python-versions:
        description: "Array of Python versions to test on, in string format"
        required: true
        type: string


jobs:

  lint:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: "Set up GitHub repository"
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v3
        with:
          python-version: ${{ fromJSON(inputs.python-versions)[0] }}
      - name: "Install Python dependencies"
        run: |
          pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install --no-cache-dir --quiet ".[lint]"
          pip list
      - name: "Check code format"
        run: |
          make check

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    steps:
      - name: "Set up GitHub repository"
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Python dependencies"
        run: |
          pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install --no-cache-dir --quiet ".[test]"
          pip list
      - name: "Run tests"
        run: |
          make test
