name: Continuous Integration

on:
  workflow_call:
    inputs:
      python-versions:
        description: "Array of Python versions to test on, in string format"
        required: true
        type: string
    secrets:
      private-ssh-keys:
        description: "Array of private packages SSH deploy keys, in string format"
        required: false

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    steps:
      - name: "Set up GitHub repository"
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Set up private packages SSH keys"
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.ssh-keys }}
      - name: "Install Python dependencies"
        run: |
          pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install --no-cache-dir --quiet ".[test]"
          pip list
      - name: "Run tests"
        run: |
          make test
